#!/bin/bash

echo '['

while read name
do
    read street
    read city
    read phone
    echo -n "{\"name\":\"$name\",\"street\":\"$street\",\"city\":\"$city\",\"phone\":\"$phone\"}"
    read blank || break
    echo ,
done

echo
echo ']'
